"""
Provides constant values for the `greeting.tests` module.
Define constants here to be used for test files.

@option   Consider adding `TEST_` prefix to constants.
"""


# OAuth2 specific 
TEST_CLIENT_ID: str = 'test_id'
TEST_CLIENT_SECRET: str = 'test_secret'
TEST_CREDENTIAL: str = f'{TEST_CLIENT_ID}:{TEST_CLIENT_SECRET}'
TEST_ACCESS_TOKEN: str = 'test_access_token'

# Generated by script: ./utility/scripts/oauth/encoder.py
# with the test credential constant
TEST_ENCODED_CREDENTIAL: str = 'dGVzdF9pZDp0ZXN0X3NlY3JldA=='

