from unittest import TestCase

from unittest.mock import patch

from greetings.views import encode_credentials


class AuthenticationTestCase(TestCase):
  """
  Test case to test the auth flow process to acquire an
  access token for the grant type: "client credentials".
  """
  
  def setUp(self) -> None:
    self.client_id = 'test_id'
    self.client_secret = 'test_secret'
    
  def test_should_base64_encode_the_provided_client_id_and_secret(self) -> None:
    # Given
    # generated by script: ./utility/scripts/oauth/encoder.py
    expected = 'dGVzdF9pZDp0ZXN0X3NlY3JldA=='
    
    # When
    actual = encode_credentials(self.client_id, self.client_secret)
    
    # Then
    self.assertIsInstance(actual, str)
    self.assertEqual(actual, expected)
