# Generated by Django 4.2.2 on 2023-07-02 13:33

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Greeting",
            fields=[
                (
                    "greeting_id",
                    models.UUIDField(
                        default=uuid.uuid5,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("greeting_text", models.CharField(max_length=50, unique=True)),
                ("greeting_created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["greeting_created_at"],
            },
        ),
    ]
